apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: monetization-proxy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - monetization-proxy.k8s.downey.dev
    secretName: monetization-proxy
  rules:
  - host: monetization-proxy.k8s.downey.dev
    http:
      paths:
      - backend:
          serviceName: monetization-proxy-example
          servicePort: 8080
